name: buybuy
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - Django==4.2.7
    - Pillow==10.1.0
    - django-crispy-forms==2.1
    - crispy-bootstrap5==0.7
    - python-decouple==3.8

